### ISSUE TITLE
Vesion 3.1 listed in the master readme is not available

### ISSUE THREAD

**Issue by fstani** [moussetc/mattermost-plugin-spoiler#24]
**Describe the bug**
The version 3.1 that should include security fixes is not available under the releases

**To Reproduce**
1. Check releases page

**Expected behavior**
Expected to see release 3.1 to download

**Mattermost information**
- server version: 5.39.2
- client version: Desktop 4.71
- plugin version: v 3.0.0

**Comment by moussetc** [comment]
Good catch, here you go https://github.com/moussetc/mattermost-plugin-spoiler/releases/tag/v3.1.0
