### ISSUE TITLE
Unable to Start Plugin on MM version 6.3

### ISSUE THREAD

**Issue by djderan** [moussetc/mattermost-plugin-spoiler#25]
> Server Logs.
{"timestamp":"2022-02-04 10:18:29.797 -05:00","level":"error","msg":"Unable to activate plugin","caller":"app/plugin.go:142","plugin_id":"com.github.moussetc.mattermost.plugin.spoiler","error":"unable to start plugin: com.github.moussetc.mattermost.plugin.spoiler: Unrecognized remote plugin message: \n\nThis usually means that the plugin is either invalid or simply\nneeds to be recompiled to support the latest protocol."}

**Comment by fpeterschmitt** [comment]
recompiling the server plugin and replacing the binary is enough to get it working again

**Comment by fpeterschmitt** [comment]
assuming you have go installed, `make server` is enough.

then the binaries are in `server/dist`

**Comment by moussetc** [comment]
I could not reproduce the issue using the latest version of the plugin ([3.1.0](https://github.com/moussetc/mattermost-plugin-spoiler/releases/tag/v3.1.0)) and the Docker preview of [Mattermost Server 6.4.0](https://hub.docker.com/layers/mattermost/mattermost-preview/6.4.0/images/sha256-402699df69ebf64e8d5ec26e5cfbc23283da7667cd1c2579b5fa10a5a8b6b7fc?context=explore).

@djderan What version of the plugin are you using? Did you compile it youself or download it from Github ? On what server system (OS, amd64 or something else, etc.) was it installed ? What is an installation from scratch or due to an update?

@fpeterschmitt did you have the same issue? If yes, what version of Go did you use to recompile? (this error usually appears when there's an incompatibility between versions)

**Comment by djderan** [comment]
I downloaded the latest version on GitHub, I did not compile it myself.  I am running Mattermost 6.3.0 in docker and the installation was from scratch.

**Comment by fpeterschmitt** [comment]
i'm not sure when the plugin stopped working, as we don't use it very often.
i recompiled with go 1.17.x iirc, i doubt it was 1.18

**Comment by moussetc** [comment]
Thank you both for your answers. Sadly, I can't even reproduce the issue with a MM 6.3.0 custom Docker image, so it might be tied to some obscure system-dependant go compatibility issue... 

If I try to build a release with a more recent version of Go, would one of you agree to test it on your server to ensure that the issue is actually fixed?

**Comment by djderan** [comment]
Yeah I have no issue testing it out!

**Comment by fpeterschmitt** [comment]
i can also try, at your convenience

**Comment by moussetc** [comment]
Sorry for the delay, I had some trouble with my dev environment.

I think the issue is not the Go version (if only because I'm compiling the plugin with the same version that is used to compile MM server), but rather a libc incompatibility.

To check that, could you:
 - set your server logs to DEBUG level (System Console > Logging > File Log Level: DEBUG)
 - retry to install&activate the faulty version of the plugin
 - give me the debug logs

Typically,if you find lines like:
```
{"timestamp":"2022-03-23 20:29:09.582 Z","level":"debug","msg":"plugins/com.github.moussetc.mattermost.plugin.spoiler/server/dist/plugin-linux-amd64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by plugins/com.github.moussetc.mattermost.plugin.spoiler/server/dist/plugin-linux-amd64)","caller":"..."}
```
around the error message, it would confirm my hypothesis.
If not, it still would be very interesting to see the debug logs that happen just before the error in order to find the real cause.

**Comment by fpeterschmitt** [comment]
for some reason i cannot reproduce the problem… i tested 3.0.0, 3.1.0 and my own binary rebuilt from master… i don't understand what happened :sweat_smile: a friend tried to use the `/spoiler` command, it didn't work.

i restarted the server, still broken.

downloaded the latest 3.1.0, still wasn't working. then rebuilt, pushed only the binary, and it worked… i don't get it

**Comment by djderan** [comment]
> Sorry for the delay, I had some trouble with my dev environment.
> 
> I think the issue is not the Go version (if only because I'm compiling the plugin with the same version that is used to compile MM server), but rather a libc incompatibility.
> 
> To check that, could you:
> 
>     * set your server logs to DEBUG level (System Console > Logging > File Log Level: DEBUG)
> 
>     * retry to install&activate the faulty version of the plugin
> 
>     * give me the debug logs
> 
> 
> Typically,if you find lines like:
> 
> ```
> {"timestamp":"2022-03-23 20:29:09.582 Z","level":"debug","msg":"plugins/com.github.moussetc.mattermost.plugin.spoiler/server/dist/plugin-linux-amd64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by plugins/com.github.moussetc.mattermost.plugin.spoiler/server/dist/plugin-linux-amd64)","caller":"..."}
> ```
> 
> around the error message, it would confirm my hypothesis. If not, it still would be very interesting to see the debug logs that happen just before the error in order to find the real cause.

`{"timestamp":"2022-03-24 16:51:27.085 -04:00","level":"error","msg":"Unable to activate plugin","caller":"app/plugin.go:142","plugin_id":"com.github.moussetc.mattermost.plugin.spoiler","error":"unable to start plugin: com.github.moussetc.mattermost.plugin.spoiler: Unrecognized remote plugin message: \n\nThis usually means that the plugin is either invalid or simply\nneeds to be recompiled to support the latest protocol."}
{"timestamp":"2022-03-24 16:51:27.124 -04:00","level":"error","msg":"Unable to activate plugin","caller":"app/plugin.go:142","plugin_id":"com.github.moussetc.mattermost.plugin.spoiler","error":"unable to start plugin: com.github.moussetc.mattermost.plugin.spoiler: Unrecognized remote plugin message: \n\nThis usually means that the plugin is either invalid or simply\nneeds to be recompiled to support the latest protocol."}`

**Comment by fpeterschmitt** [comment]
i was able to reproduce, for some reason:

```
iler"}
{"timestamp":"2022-03-28 09:40:32.699 +02:00","level":"debug","msg":"starting plugin","caller":"plugin/hclog_adapter.go:52","plugin_id":"com.github.moussetc.mattermost.plugin.spoiler","wrapped_extras":"path../plugins/com.github.moussetc.mattermost.plugin.spoiler/server/dist/plugin-linux-amd64args[../plugins/com.github.moussetc.mattermost.plugin.spoiler/server/dist/plugin-linux-amd64]"}
{"timestamp":"2022-03-28 09:40:32.753 +02:00","level":"debug","msg":"plugin started","caller":"plugin/hclog_adapter.go:52","plugin_id":"com.github.moussetc.mattermost.plugin.spoiler","wrapped_extras":"path../plugins/com.github.moussetc.mattermost.plugin.spoiler/server/dist/plugin-linux-amd64pid100349"}
{"timestamp":"2022-03-28 09:40:32.753 +02:00","level":"debug","msg":"waiting for RPC address","caller":"plugin/hclog_adapter.go:52","plugin_id":"com.github.moussetc.mattermost.plugin.spoiler","wrapped_extras":"path../plugins/com.github.moussetc.mattermost.plugin.spoiler/server/dist/plugin-linux-amd64"}
{"timestamp":"2022-03-28 09:40:35.753 +02:00","level":"warn","msg":"plugin failed to exit gracefully","caller":"plugin/hclog_adapter.go:72","plugin_id":"com.github.moussetc.mattermost.plugin.spoiler"}
{"timestamp":"2022-03-28 09:40:35.754 +02:00","level":"debug","msg":"plugin process exited","caller":"plugin/hclog_adapter.go:52","plugin_id":"com.github.moussetc.mattermost.plugin.spoiler","wrapped_extras":"path../plugins/com.github.moussetc.mattermost.plugin.spoiler/server/dist/plugin-linux-amd64pid100349errorsignal: killed"}
{"timestamp":"2022-03-28 09:40:35.754 +02:00","level":"error","msg":"Unable to activate plugin","caller":"app/plugin.go:142","plugin_id":"com.github.moussetc.mattermost.plugin.spoiler","error":"unable to start plugin: com.github.moussetc.mattermost.plugin.spoiler: timeout while waiting for plugin to start"}
{"timestamp":"2022-03-28 09:41:28.365 +02:00","level":"debug","msg":"Access to route for non-existent plugin","caller":"app/plugin_requests.go:37","missing_plugin_id":"com.github.moussetc.mattermost.plugin.spoiler","url":"/show","error":"plugin not found: com.github.moussetc.mattermost.plugin.spoiler"}
{"timestamp":"2022-03-28 09:42:56.220 +02:00","level":"warn","msg":"Skipping sync for unmanaged plugin","caller":"app/plugin.go:279","plugin_id":"com.github.moussetc.mattermost.plugin.spoiler"}
{"timestamp":"2022-03-28 09:43:09.845 +02:00","level":"debug","msg":"starting plugin","caller":"plugin/hclog_adapter.go:52","plugin_id":"com.github.moussetc.mattermost.plugin.spoiler","wrapped_extras":"path../plugins/com.github.moussetc.mattermost.plugin.spoiler/server/dist/plugin-linux-amd64args[../plugins/com.github.moussetc.mattermost.plugin.spoiler/server/dist/plugin-linux-amd64]"}
{"timestamp":"2022-03-28 09:43:09.845 +02:00","level":"debug","msg":"plugin started","caller":"plugin/hclog_adapter.go:52","plugin_id":"com.github.moussetc.mattermost.plugin.spoiler","wrapped_extras":"path../plugins/com.github.moussetc.mattermost.plugin.spoiler/server/dist/plugin-linux-amd64pid100627"}
{"timestamp":"2022-03-28 09:43:09.845 +02:00","level":"debug","msg":"waiting for RPC address","caller":"plugin/hclog_adapter.go:52","plugin_id":"com.github.moussetc.mattermost.plugin.spoiler","wrapped_extras":"path../plugins/com.github.moussetc.mattermost.plugin.spoiler/server/dist/plugin-linux-amd64"}
{"timestamp":"2022-03-28 09:43:12.846 +02:00","level":"warn","msg":"plugin failed to exit gracefully","caller":"plugin/hclog_adapter.go:72","plugin_id":"com.github.moussetc.mattermost.plugin.spoiler"}
{"timestamp":"2022-03-28 09:43:12.848 +02:00","level":"debug","msg":"plugin process exited","caller":"plugin/hclog_adapter.go:52","plugin_id":"com.github.moussetc.mattermost.plugin.spoiler","wrapped_extras":"path../plugins/com.github.moussetc.mattermost.plugin.spoiler/server/dist/plugin-linux-amd64pid100627errorsignal: killed"}
{"timestamp":"2022-03-28 09:43:12.848 +02:00","level":"error","msg":"Unable to activate plugin","caller":"app/plugin.go:142","plugin_id":"com.github.moussetc.mattermost.plugin.spoiler","error":"unable to start plugin: com.github.moussetc.mattermost.plugin.spoiler: timeout while waiting for plugin to start"}
```

Some kind of timeout.

Using the rebuilt binary works. But no "glibc" message anywhere.

**Comment by moussetc** [comment]
Bug closed for inactivity.

Feel free to comment if you still encounter the error.
