### ISSUE TITLE
Screen blanks when enabling redacted mode

### ISSUE THREAD

**Issue by 143mailliw** [moussetc/mattermost-plugin-spoiler#7]
When I enable Redacted mode, the screen blanks out (looks like the loading screen but with out the three dots). I'm on Mattermost 5.10, Ubuntu 18.04, Nginx and MariaDB, if it's relevant.

**Comment by moussetc** [comment]
Could you tell me what's your browser - if it's Chrome, then it's probably related to #5 (you can check the browser console logs), which will be fixed in the upcoming version.

**Comment by 143mailliw** [comment]
It's chrome. However, I've compiled the latest version (which seems to have the fix), and it still does not function.

**Comment by moussetc** [comment]
No error in the broswer console? Or in the mattermost server logs?

**Comment by 143mailliw** [comment]
Turns out the update didn't push properally. Refreshing seemed to have fixed it.
