### ISSUE TITLE
Doesn't work in threads

### ISSUE THREAD

**Issue by Fallstar** [moussetc/mattermost-plugin-spoiler#8]
Hi,

Thanks for this plugin, it's great!
There's just one problem we're encountering: It doesn't seem to work in threads. When using the reply feature, it makes a new message out of the thread.

Do you know how we could make it work?
(I'm willing to help if you know how to do it but don't have time.)

Thanks in advance!

**Comment by moussetc** [comment]
Thanks for the report! It's patched up in the latest version, please let me know if there is any further trouble.

**Comment by Fallstar** [comment]
Wow, what efficiency! 
Thanks !
